language: php

sudo: false

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: nightly
    allow_failures:
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest'
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - COMPOSER_FLAGS=''

install:
    - composer update $COMPOSER_FLAGS

script:
    - php bin/phpspec run
    - php bin/phpunit
